name: banxico
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.3
  - matplotlib
  - seaborn=0.13.2
  - requests=2.31.0
  - pip
  - pip:
      - streamlit
      - python-dotenv==1.0.1

