name: banxico
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.3
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - requests=2.31.0
  - pip:
      - python-dotenv==1.0.1
      - streamlit
